apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: dev@livesmart.co.jp
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # TODO Need to check once
      name: letsencrypt-production-account-key
    solvers:
      - http01:
          ingress:
            class: nginx