output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value = module.eks.kubeconfig
}

output "mysql_host" {
  description = "MySQL instance host"
  value = aws_db_instance.mariadb.address
}

output "mysql_port" {
  description = "MySQL instance host"
  value = aws_db_instance.mariadb.port
}

output "mysql_username" {
  description = "MySQL instance username"
  value = aws_db_instance.mariadb.username
}
output "mysql_password" {
  description = "MySQL instance password"
  value = aws_db_instance.mariadb.password
}


output "redis_address" {
  value = aws_elasticache_cluster.redis.cache_nodes.*.address
}


output "mongo_username" {
  description = "DocDB instance username"
  value = aws_docdb_cluster.mongo.master_username
}
output "mongo_password" {
  description = "DocDB instance password"
  value = aws_docdb_cluster.mongo.master_password
}

output "mongo_port" {
  value = aws_docdb_cluster.mongo.port
}

output "mongo_host" {
  value = aws_docdb_cluster.mongo.endpoint
}


output "docker_repo_web" {
  value = concat(aws_ecr_repository.server-web.*.repository_url, list(""))[0]
}

output "docker_worker_web" {
  value = concat(aws_ecr_repository.worker-app.*.repository_url, list(""))[0]
}

output "bastion_host_address" {
  value = aws_instance.bastion.public_ip
}