{{- if .Values.scaling.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
    name: {{ include "vernemq.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "vernemq.name" . }}
        helm.sh/chart: {{ include "vernemq.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: StatefulSet
        name: {{ include "vernemq.fullname" . }}
    minReplicas: {{ .Values.scaling.minReplicas }}
    maxReplicas: {{ .Values.scaling.maxReplicas }}
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: {{ .Values.scaling.targetUtilization }}
        - type: Resource
          resource:
              name: memory
              target:
                  type: Utilization
                  averageUtilization: {{ .Values.scaling.targetUtilization }}
{{- end }}
