---
apiVersion: v1
kind: Secret
metadata:
  name: internal-resources
  namespace: b2b-application
data:

  # COMMON
  # ----------------------------------------------------------------
  
  #mongoDB name
  APP_MONGO_DB: bHNfc2VydmVy

  APP_MQTT_HOST: bXF0dC1iMmItZGV2LmxpdmVzbWFydC5jby5qcA==
  APP_MQTT_PASS: bHNtcXR0
  APP_MQTT_PORT: MTg4NQ==
  APP_MQTT_USER: bXF0dGNsaQ==

  APP_RABBITMQ_HOST: YjJiLXJhYmJpdG1xLWhhLmIyYi1uZXR3b3Jr
  APP_RABBITMQ_PASS: NUNkNVZYb2ozUmZCTW5nag==
  APP_RABBITMQ_PORT: NTY3Mg==
  APP_RABBITMQ_USER: Z3Vlc3Q=

  APP_SMTP_HOST: c210cC5zZW5kZ3JpZC5uZXQ=
  APP_SMTP_PASSWORD: U0cuODg3UnVTTzRUdWlTV1Z6b3NhU0U4US5WUEVGdjd3Tm94R3pVazVWQ254YUZ5VndabUhjb3BUOWo0a1p4ZDdKaEFZ
  APP_SMTP_PORT: NTg3
  APP_SMTP_SECURE: dHJ1ZQ==
  APP_SMTP_USER: YXBpa2V5

  #IOS Push certificates paths
  APP_B2B_IOS_CERT_PATH: L3JhYmJpdC1tcS9jZXJ0cy9iMmItY2VydC1zdGFnZS5wZW0=
  APP_B2B_IOS_KEY_PATH: L3JhYmJpdC1tcS9jZXJ0cy9iMmIta2V5LXN0YWdlLnBlbQ==
  APP_B2B_IOS_P12: L3JhYmJpdC1tcS9jZXJ0cy9iMmItc3RhZ2UucDEy
  APP_TG_IOS_CERT_PATH: L3JhYmJpdC1tcS9jZXJ0cy90b2t5b2dhcy1jZXJ0LXN0YWdlLnBlbQ==
  APP_TG_IOS_KEY_PATH: L3JhYmJpdC1tcS9jZXJ0cy90b2t5b2dhcy1rZXktc3RhZ2UucGVt
  APP_TG_IOS_P12: L3JhYmJpdC1tcS9jZXJ0cy90b2t5b2dhcy1zdGFnZS5wMTI=

  APP_APPLE_CERT_PASSPHRASE: ""
  APP_APPLE_FEDBACK_URL: ZmVlZGJhY2suc2FuZGJveC5wdXNoLmFwcGxlLmNvbQ==  # for prod use, feedback.push.apple.com, for developement use, feedback.sandbox.push.apple.com
  APP_APPLE_NOTIFICATION_URL: Z2F0ZXdheS5zYW5kYm94LnB1c2guYXBwbGUuY29t  # for prod use, gateway.push.apple.com, for developement use, gateway.sandbox.push.apple.com

  APP_CHANNEL_ACCESS_TOKEN: OTlPNEhHZnpDTTdVRkpIdDlFeDVQTzVkTUNjQ3dHSVlmRVQ2U2wzZGtzNW9UMGZKZTd0b05aSFRSZkVmcjN5dy9sNlpBSU9WWkxjM1dXYkZSS3NtMTJpMWdySFNXc3dhT3VOUThDSXU2WE1hRkNEUFh6NkQrRHZacnhMamwvc3NBRy9uOG80TEZhTXpnWmdzMlJNQm13ZEIwNHQ4OS8xTy93MWNEbnlpbEZVPQ==
  APP_CHANNEL_SECRET: ODQ5M2FkMTNhMDUzM2M3ZGY0Yjc1MjA0ZmEyNWE4ZDE=

  APP_GCM_KEY: ""
  APP_GCM_SANDBOX: dHJ1ZQ==

  APP_ALEXA_REDIRECTION_URL: aHR0cHM6Ly9waXRhbmd1aS5hbWF6b24uY29tL2FwaS9za2lsbC9saW5rL00yUE5WSEs4TEdHVTU0
  APP_GHOME_RESYNC_KEY: QUl6YVN5RGdfM0d0NzgzUnB5aFRTemFsRFo3d0hTbzhhbUczMnI4

  APP_IFT_CHANNEL_KEY: dGVzdF81RUdQVjFNSjV6TXptQ2drQzFwVnF1ZVpLQVNfNzNTNll0OWgwV0pkcks0MnRKam0xaWpkQ2N3Sk9SVQ==
  APP_IFT_SERVICE_KEY: dGVzdF81RUVQVjFNSjV6TXptQ2drQzFwVnF1ZVpLQVNfNzNTNll0OWgwV0pkcks0MnRKam0xaWpkQ2N3Sk9SVQ==

  APP_BESEYE_BASE_URL: aHR0cHM6Ly9vcmVnb24tcDEtc3RhZ2UtYXBpLTEuYmVzZXllLmNvbQ==
  APP_BESEYE_CLIENT_ID: NWNiZmEyZWE2OGE3YjcwMDQ0YmQwNzQzMWE4MzAxNDllNThkMzM5N2U3NDhhZTJkYzg2Y2E1MTc2NWI0YTMwZA==
  APP_BESEYE_CLIENT_SECRET: N2UyNmMyMjg1NjE2NDgxZDU2ZGM3MDhlYTNkYTA4OTM4MzA1YTU5ZGRkOTgxYmEzOWI5NWNlYThkN2RjOGM4ZA==


  # APP SERVER
  # ----------------------------------------------------------------
  
  # app base url
  APP_BASE_URL: aHR0cHM6Ly9iMmItZGV2LmxpdmVzbWFydC5jby5qcA==

  APP_AI_URL: aHR0cHM6Ly9vcWNtbnJ6bHE5LmV4ZWN1dGUtYXBpLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vZGV2L2FkYXB0aXZlLWRldi12Mi1iMmI=

  APP_NEW_REMOTE_URL: aHR0cHM6Ly9jb250cm9sd2ViLWRldi5saXZlLXNtYXJ0LmlvL2JvdC8jL2RldmljZXZpZXc/dG9rZW5faWQ9
  APP_BASE_DOMAIN: ""
  APP_CS_DOMAIN: c3VwcG9ydC1kYXNoYm9hcmQuZGV2LmxpdmVzbWFydA==
  APP_WC_DOMAIN: Y29udHJvbHdlYi1kZXY=

  # notification keys
  APP_FCM_SENDERID: NzU4NTA2Njg4MTc0
  APP_FCM_SERVER_KEY: QUFBQXNKcUZqcTQ6QVBBOTFiRlNxOU01RW54dWg0ZjB0SkItWi1zY0Q1aDYxMWR3VXdfcVZEYnJuOFpHQ3FDcXc0QUgteW00bnNndThVR1B4YkxwWG9OYUJ3S3ExemJzeUp2Z09jTEs2MTNwQVIxa0pjaC1CN3JFYWl5aGRBMVhHNFRLZlQzZFM4MHJfekdrYlFJSUdmNVY=
  
  #login verify host
  APP_LOGIN_VERFY_HOST: aHR0cHM6Ly9iMmItZGV2LmxpdmVzbWFydC5jby5qcA==
  APP_LOGIN_VERFY_HOST_TOKYOGAS: aHR0cHM6Ly9iMmItZGV2LmxpdmVzbWFydC5jby5qcA==
 
  # line webhook
  APP_LS_INFRA_CALLBACK: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZXNtYXJ0L0xpdmVTbWFydExvZ2luU3RhdHVz

  TOKYOGAS_FROM_EMAIL: dG9reW9nYXNAbm9yZXBseS5saXZlc21hcnQuY28uanA=

  APP_JWT_SECRET : bGl2ZXNtYXJ0and0

  APP_HUB_CMD_API_KEY: eXZmNHhseHg2a2xpdmVzbWFydA==

  APP_AI_V3_LAMBDA_URL: aHR0cHM6Ly9vcWNtbnJ6bHE5LmV4ZWN1dGUtYXBpLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vZGV2L2FkYXB0aXZlLWRldi12Mg==

  # dynamoDB
  APP_DYNAMODB_POOL_ID: YXAtbm9ydGhlYXN0LTE6Nzk3MWQwY2YtYjI4YS00MjNjLThmOTUtN2M1MjQwYmMxYjEx
  APP_AWS_REGION: YXAtbm9ydGhlYXN0LTE=
  APP_AWS_ACCOUNT_ID: MDE3OTg5MjI3MzY3
  APP_DYNAMODB_TABLENAME: YjJiX2FpX2RldmljZV92M19kZXY=

  # trigger rule
  APP_SQS_POOLID: YXAtbm9ydGhlYXN0LTE6NGM3OGEyZGYtMzI4Mi00MDg0LTk4OTQtMmM4ZWQzOTQ1NjE4
  APP_SQS_RESOURCE_URL: aHR0cHM6Ly9zcXMuYXAtbm9ydGhlYXN0LTEuYW1hem9uYXdzLmNvbS8wMTc5ODkyMjczNjcvdHJpZ2dlcl9iMmJfZGV2
  APP_TIME_TRIGGER_DYNAMODB: YjJiX2Rldl90aW1lX3RyaWdnZXI=
  APP_DEVICE_TRIGGER_DYNAMODB: YjJiX2Rldl9kZXZpY2VfdHJpZ2dlcg==
  APP_LINE_NOTIFICATION_WEBHOOK: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZVNtYXJ0L1JlYWxUaW1lUHVzaE5vdGlmaWNhdGlvbg==
  APP_BUSINESS_TYPE: Mg==
  FIRMWARE_API_ENDPOINT: aHR0cHM6Ly80ejQxMXl0NGQ2LmV4ZWN1dGUtYXBpLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vZGV2Lw==
  FIRMWARE_API_KEY: SVV6d1VsTUVzeDV4czRpS1dVV0piYUNrbGJMUXNmRjM4bFVRcGhhVQ==

  # watching over
  TWILIO_ACCOUNT_SID: QUM2NDY0YWQ3YTRhOGIwZGJiNDgxOTkyYTY3ZGFiYWI1Yg==
  TWILIO_AUTH_TOKEN: YWEzOGMzNzljMzE5ZDIyZWVmMTZiMGMwZDA2N2JkOTg=
  TWILIOFROMNO: KzE4MzM3MTcxMDUy
  APP_NOTIFICATION_DYNAMODB_TABLENAME: d2F0Y2hpbmdfb3Zlcl9ub3RpZmljYXRpb24=

  # third party devices
  APP_THIRD_PARTY_DEVICES_API: aHR0cHM6Ly8xZ3QwNHNtcWE1LmV4ZWN1dGUtYXBpLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vYjJiLXN0YWdlL3R1eWEtYjJiLXN0YWdlLXYx
  APP_THIRD_PARTY_DEVICES_API_API_KEY: dUNjSmtYZk50NzRZUjRtbTBWb2Z4NDB3czQ5dlJFSXY3ajlVV05XUw==

  APP_X_API_KEY: dTg2N293MWhzdFVUQWF5WlhHbHY4cUduQ3dzTlNuWjZVZmR4cWxGYQ==
  APP_TP_JWTSECRET: bHN0aGlyZHBhcnR5

  APP_INTERNAL_X_API_KEY: N2UyNmMyMjg1NjE2NDgxZDU2ZGM3MDhlYTNkYTA4OTM4MzA1
  APP_MQTT_SERVER_LINKS: bXF0dC1iMmItZGV2LmxpdmVzbWFydC5jby5qcDoxODg1
  APP_SERVER_LINKS: aHR0cHM6Ly9iMmItZGV2LmxpdmVzbWFydC5jby5qcA==
  APP_BASE_MQTT_SERVER_LINKS: anB0ZXN0bXF0dC5saXZlc21hcnQuY28uanA6MTg4NQ==
  APP_BASE_SERVER_LINKS: aHR0cHM6Ly9qcHRlc3QubGl2ZXNtYXJ0LmNvLmpw

  APP_LOCO_BUZZ_CALL_BACK_URL: aHR0cHM6Ly9sc2FuYWx5dGljczEubGl2ZXNtYXJ0LmNvLmpwL0xpdmVzbWFydC9MaXZlU21hcnRMb2dpblN0YXR1cw==
  APP_LOCO_BUZZ_NOTIFICATION_URL: aHR0cHM6Ly9sc2FuYWx5dGljczEubGl2ZXNtYXJ0LmNvLmpwL0xpdmVzbWFydC9MaXZlU21hcnRTdGF0ZUNoYW5nZWROb3RpZmljYXRpb24=

  APP_RINNAI_API: aHR0cHM6Ly90c3ljMTM4YXVrLmV4ZWN1dGUtYXBpLmFwLW5vcnRoZWFzdC0xLmFtYXpvbmF3cy5jb20vZGV2


 # DASHBOARD Server
 # ----------------------------------------------------------------
  PORT: ODA4MA==
  HOST: MC4wLjAuMA==
  NODE_ENV: cHJvZHVjdGlvbg==
  MAILGUN_DOMAIN: bm9yZXBseS5saXZlc21hcnQuY28uanA=
  MAILGUN_API_KEY: YTg0ODFmOTczM2NjODE0NjNlNDU2ZjUwMzM5OWY1MTQtMGU2ZThjYWQtMDJiNmIxOTg=
  BOT_BASIC_USERNAME: bHNib3Q=
  BOT_BASIC_PASSWORD: Ym90bG9jb2J1enpAMjAxOQ==
  JWT_SECRET_KEY: aDNyekBnaW4z
  JWT_KEY_REQ: bGl2ZXNtYXJ0
  MAPS_APP_CODE: UnN4N2toOFZqejdqZU9yVnlhc0JGUQ==
  MAPS_APP_ID: WW4xbXNQM0VRWnNGaU5TU0dXWFE=
  DASHBOARD_WEB_BASE_URL: aHR0cHM6Ly9kYXNoYm9hcmQtZGV2LmxpdmVzbWFydC5jby5qcA==
  APP_LS_DASHBOARD_DOMAIN: aHR0cHM6Ly9kYXNoYm9hcmQtZGV2LmxpdmVzbWFydC5jby5qcA==
  APP_TOKYOGAS_DASHBOARD_DOMAIN: aHR0cHM6Ly90b2t5b2dhcy1kYi1zdGFnZS5saXZlc21hcnQuY28uanA=
  BOT_ACCOUNT_REG: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZVNtYXJ0L1Byb3BlcnR5TWFuYWdlckxvZ2lu
  BOT_LOGIN: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZVNtYXJ0L1BNU2Vzc2lvbkFjdGl2ZQ==
  BOT_LOGOUT: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZVNtYXJ0L1BNU2Vzc2lvbkluYWN0aXZl
  BOT_AUTH_TOKEN: YWFlYTg2NGUtOTA1OC00NzVjLThmOTktZGMwNjIzZmM3ZWMy
  BOT_MOVEOUT: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZXNtYXJ0L1Jlc2lkZW50TW92ZU91dA==
  BOT_DEFAULT_BRAND_CODE: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvbGl2ZXNtYXJ0L0dldERlZmF1bHRCcmFuZElk
  BOT_UPDATE_BRAND_CODE: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvTGl2ZXNtYXJ0L1VwZGF0ZUJyYW5kQ29kZUJ5UE1JRA==
  APP_SERVER_URL: aHR0cHM6Ly9iMmItZGV2LmxpdmVzbWFydC5jby5qcA==
  BOT_VALIDATE: aHR0cHM6Ly9zdGFnZS1sc2FuYWx5dGljcy5saXZlc21hcnQuY28uanAvbGl2ZXNtYXJ0L0lzVmFsaWRCcmFuZElE

  JWT_SECRET_CAPTCHA: NkxjRW9MWVVBQUFBQUpkaXQ1R1lxZ1V0c014ekplZlBXTTZQSkRsQg==


  # DASHBOARD WEB
  # ----------------------------------------------------------------

  APP_API_KEY: azdIckUzZjFvSVllVHhmUHFyMjZoUHhiOFVOb2xHNXlnTDJPazhDbEhBcw==
  APP_APP_CODE: MQ==
  APP_APP_ID: MQ==
  APP_API_URL : aHR0cHM6Ly9kYXNoYm9hcmQtYXBpLmRldi5saXZlLXNtYXJ0LmlvL2FwaS8=

  # OTHER
  APP_ALL_ADMIN_MAIL: ZGhpbmVzaC5zb3JuYWtpbGlAbGl2ZXNtYXJ0LmNvLmpwIHNhdGhpc2hrdW1hci5zdWRhbGFpbWFuaUBsaXZlc21hcnQuY28uanAgcmFtdmlub3RoLmthc2lwYW5kaWFuQGxpdmVzbWFydC5jby5qcCBieXVuZ2pvLmFobkBsaXZlc21hcnQuY28uanA=
  APP_ADMIN_MAIL : ZGhpbmVzaC5zb3JuYWtpbGlAbGl2ZXNtYXJ0LmNvLmpwIHNhdGhpc2hrdW1hci5zdWRhbGFpbWFuaUBsaXZlc21hcnQuY28uanAgcmFtdmlub3RoLmthc2lwYW5kaWFuQGxpdmVzbWFydC5jby5qcCBieXVuZ2pvLmFobkBsaXZlc21hcnQuY28uanA=
  APP_IR_REMOTES_URL: aHR0cDovL3dlYi5saXZlc21hcnQuY28uanAvV2ViQXBwL2xzLWxpbmUtc3RhZ2Uv
  APP_REMOTES_URL: aHR0cDovL2JsYXplaW5ub3ZhdGlvbnMuY29tL1dlYkFwcC9iMS1saW5lLXN0YWdlLw==

---

apiVersion: v1
kind: Secret
metadata:
  namespace: network
  name: nginx-auth
data:
  auth: CnVzZXI6JGFwcjEkVVVmVk0vaFckYW9jTWFLLzlsMmdKVm5xOFRmRk9JLg==
