replicaCount: 1

image:
  repository: hjacobs/kube-ops-view
  tag: 0.11
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 400m
    memory: 128Mi
  requests:
    cpu: 300m
    memory: 64Mi

ingress:
  enabled: true
  path: /
  hostname: kubeops-2c98ao.dev.live-smart.io
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: network/nginx-auth
  tls:
     - secretName: kube-ops-view-web-tls
       hosts:
         - kubeops-2c98ao.dev.live-smart.io
rbac:
  create: true
