apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: node-high-priority
value: 1000000
globalDefault: false
description: "This priority class should be used for node high priority service pods only."