{
 "title": "Application advanced metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": "label_values(http_request_duration_seconds_count, service)"
   }
  ]
 },
 "panels": [
  { "title": "HTTP metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Requests Count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))",
     "legendFormat": " 95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "HTTP Average response time by path",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le, path))",
     "legendFormat": "{{path}}  - 95th"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le, path))",
     "legendFormat": "{{path}} - 90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le, path))",
     "legendFormat": "{{path}} - 50th"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Application errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ls_app_exceptions[30s]) + increase(ls_app_rejections[30s]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Application errors by service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ls_app_exceptions[30s])) by (service)",
     "legendFormat": "{{service}} - exceptions"
    },
    {
     "expr": "sum(increase(ls_app_rejections[30s])) by (service)",
     "legendFormat": "{{service}}  - rejections"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(nodejs_eventloop_lag_seconds) by (service)",
     "legendFormat": "Total {{service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_external_memory_bytes) by (service)",
     "legendFormat": "Total {{service}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_heap_space_size_total_bytes) by (service, space)",
     "legendFormat": "Total {{service}} {{space}}"
    }
   ]
  },
  {
   "title": "CPU time usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(process_cpu_system_seconds_total[30s])) by (service, space)",
     "legendFormat": "Total {{service}} {{space}}"
    }
   ]
  }
 ]
}
{
 "title": "Application basic metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": "label_values(http_request_duration_seconds_count, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Web application instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (pod) (up{job=~\".*middleware-web\"}))"
    }
   ]
  },
  {
   "title": "Worker application instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (pod) (up{job=~\".*middleware-workers\"}))"
    }
   ]
  },
  {
   "title": "Worker nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (instance) ({job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ls_app_exceptions{job=\"$job\"}[30s]) + increase(ls_app_rejections{job=\"$job\"}[30s]))"
    }
   ]
  },
  {
   "title": "HTTP Requests Count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ls_app_exceptions{job=\"$job\"}[30s]) + increase(ls_app_rejections{job=\"$job\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  }
 ]
}
{
 "title": "RabbitMQ Monitoring",
 "description": "Rabbitmq stats and alerting using RabbitMQ Exporter (https://github.com/kbudde/rabbitmq_exporter)",
 "tags": [
  "rabbitmq",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(rabbitmq_running, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Connections, channels and consumers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_connectionsTotal", "legendFormat": "connections" },
    { "expr": "rabbitmq_channelsTotal", "legendFormat": "channels" },
    { "expr": "rabbitmq_consumersTotal", "legendFormat": "consumers" }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_running", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Messages per Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_queue_messages", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Messages status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_ready)",
     "legendFormat": "{{queue}}:ready"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_published_total)",
     "legendFormat": "{{queue}}:published"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_delivered_total)",
     "legendFormat": "{{queue}}:delivered"
    },
    {
     "expr": "sum by (queue)(rabbitmq_queue_messages_unacknowledged)",
     "legendFormat": "{{queue}}:unack"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_disk_free", "legendFormat": "{{node}}:free" },
    { "expr": "rabbitmq_node_disk_free_limit", "legendFormat": "{{node}}:limit" }
   ]
  },
  {
   "title": "Used memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_mem_used", "legendFormat": "{{node}}:used" },
    { "expr": "rabbitmq_node_mem_limit", "legendFormat": "{{node}}:limit" }
   ]
  }
 ]
}