apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::017989227367:role/test2021020917502627110000000c
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
    - rolearn: arn:aws:iam::017989227367:role/test2021020917502627110000000c
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:nodes

  mapUsers: |
    - userarn: arn:aws:iam::017989227367:user/dhinesh.sornakili@livesmart.co.jp
      username: dhinesh.sornakili@livesmart.co.jp
      groups:
        - system:masters
    - userarn: arn:aws:iam::017989227367:user/sathishkumar.sudalaimani@livesmart.co.jp
      username: sathishkumar.sudalaimani@livesmart.co.jp
      groups:
        - system:masters
    - userarn: arn:aws:iam::017989227367:user/ramvinoth.kasipandian@livesmart.co.jp
      username: ramvinoth.kasipandian@livesmart.co.jp
      groups:
        - system:masters
    - userarn: arn:aws:iam::017989227367:user/taka.suzuki@livesmart.co.jp
      username: taka.suzuki@livesmart.co.jp
      groups:
        - system:masters
    - userarn: arn:aws:iam::017989227367:user/hikaru.masuta@livesmart.co.jp
      username: hikaru.masuta@livesmart.co.jp
      groups:
        - system:masters
    - userarn: arn:aws:iam::017989227367:user/sanjaywadhwani@consultant
      username: sanjaywadhwani@consultant
      groups:
        - system:masters

  mapAccounts: |