{
 "title": "Application basic metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": "label_values(http_request_duration_seconds_count, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Web application instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (pod) (up{job=~\".*middleware-web\"}))"
    }
   ]
  },
  {
   "title": "Worker application instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (pod) (up{job=~\".*middleware-workers\"}))"
    }
   ]
  },
  {
   "title": "Worker nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (instance) ({job=\"node-exporter\"}))"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(ls_app_exceptions{job=\"$job\"}[30s]) + increase(ls_app_rejections{job=\"$job\"}[30s]))"
    }
   ]
  },
  {
   "title": "HTTP Requests Count ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Requests rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"$job\"}[30s])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Average response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_request_duration_seconds_bucket{job=\"$job\"}[1m])) by (le))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Application errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(ls_app_exceptions{job=\"$job\"}[30s]) + increase(ls_app_rejections{job=\"$job\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  }
 ]
}